pipeline{
  agent any

  stages{
    stage('Clone git repo'){
      steps{
        git url: 'https://github.com/AlexKolyago/project.git',
          }
    }
    stage('Jenkins -> ansible -> Docker-compose'){
      steps{
        ansiblePlaybook disableHostKeyChecking: false, installation: 'ansible', inventory: 'ansible/inv.yaml', playbook: 'ansible/play.yaml'
      }
    }
  }
  post {
        success {
            slackSend (color: '#00FF00', message: "SUCCESSFULL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
        }
        failure {
            slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
        }
    }
}
